version: 0.1.0
experiment_name: N2V 3D
algorithm_config:
  algorithm_type: fcn
  algorithm: n2v
  loss: n2v
  model:
    architecture: UNet
    conv_dims: 3
    num_classes: 1
    in_channels: 1
    depth: 2
    num_channels_init: 32
    final_activation: None
    n2v2: false
    independent_channels: true
  optimizer:
    name: Adam
    parameters:
      lr: 0.0001
  lr_scheduler:
    name: ReduceLROnPlateau
    parameters: {}
data_config:
  data_type: tiff
  axes: ZYX
  patch_size:
  - 8
  - 64
  - 64
  batch_size: 8
  transforms:
  - name: XYFlip
    flip_x: true
    flip_y: true
    p: 0.5
  - name: XYRandomRotate90
    p: 0.5
  - name: N2VManipulate
    roi_size: 11
    masked_pixel_percentage: 0.2
    strategy: uniform
    struct_mask_axis: none
    struct_mask_span: 5
training_config:
  num_epochs: 20
  checkpoint_callback:
    monitor: val_loss
    verbose: false
    save_weights_only: false
    save_last: true
    save_top_k: 3
    mode: min
    auto_insert_metric_name: false
